services:
  frontend:
    build:
      context: ./
      target: prod
      args:
        - VITE_BACKEND_URL=${VITE_BACKEND_URL}
    container_name: frontend
    environment:
      - NGINX_HOST=${NGINX_HOST}
    depends_on:
        - backend
    networks:
      - notes
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf.template:/etc/nginx/templates/frontend.conf.template
  backend:
    image: dvp-notes-backend:1
    environment:
      - SALT=${SALT}
    networks:
      - notes
    volumes:
      - "${DB_PATH}:/usr/go/db"
networks:
  notes:
    driver: bridge